namespace TestsGenerator
{
    internal static class MultistepParticipant
    {
        public static string Code = """
            // <auto-generated>

            using System;

            namespace TestsGenerator.Abstractions
            {
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
                public sealed class MultistepParticipantAttribute : Attribute
                {
                }
            }
            """;
    }
}
